tablavisitante = {"nodes":[
{"id":1,"Equipo":"RB Leipzig","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":4,"gc":0,"DIF":4,"puntos":3},
{"id":2,"Equipo":"Bayern Muenchen","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":3,"gc":0,"DIF":3,"puntos":3},
{"id":3,"Equipo":"VfL Wolfsburg","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":3,"gc":0,"DIF":3,"puntos":3},
{"id":4,"Equipo":"Bayer 04 Leverkusen","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":3,"gc":1,"DIF":2,"puntos":3},
{"id":5,"Equipo":"Bor. Moenchengladbach","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":3,"gc":1,"DIF":2,"puntos":3},
{"id":6,"Equipo":"Borussia Dortmund","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":3,"gc":1,"DIF":2,"puntos":3},
{"id":7,"Equipo":"Fortuna Duesseldorf","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":3,"gc":1,"DIF":2,"puntos":3},
{"id":8,"Equipo":"SC Freiburg","jornada":2,"jugados":1,"PG":1,"PE":0,"PP":0,"GF":3,"gc":1,"DIF":2,"puntos":3},
{"id":9,"Equipo":"Hertha BSC","jornada":2,"jugados":1,"PG":0,"PE":1,"PP":0,"GF":2,"gc":2,"DIF":0,"puntos":1},
{"id":10,"Equipo":"1. FC Union Berlin","jornada":2,"jugados":1,"PG":0,"PE":1,"PP":0,"GF":1,"gc":1,"DIF":0,"puntos":1},
{"id":11,"Equipo":"FC Schalke 04","jornada":2,"jugados":1,"PG":0,"PE":1,"PP":0,"GF":0,"gc":0,"DIF":0,"puntos":1},
{"id":12,"Equipo":"SC Paderborn 07","jornada":2,"jugados":1,"PG":0,"PE":0,"PP":1,"GF":2,"gc":3,"DIF":-1,"puntos":0},
{"id":13,"Equipo":"Werder Bremen","jornada":2,"jugados":1,"PG":0,"PE":0,"PP":1,"GF":2,"gc":3,"DIF":-1,"puntos":0},
{"id":14,"Equipo":"1. FC Koeln","jornada":2,"jugados":1,"PG":0,"PE":0,"PP":1,"GF":1,"gc":2,"DIF":-1,"puntos":0},
{"id":15,"Equipo":"Eintracht Frankfurt","jornada":2,"jugados":1,"PG":0,"PE":0,"PP":1,"GF":1,"gc":2,"DIF":-1,"puntos":0},
{"id":16,"Equipo":"TSG Hoffenheim","jornada":2,"jugados":1,"PG":0,"PE":0,"PP":1,"GF":0,"gc":1,"DIF":-1,"puntos":0},
{"id":17,"Equipo":"1. FSV Mainz 05","jornada":2,"jugados":1,"PG":0,"PE":0,"PP":1,"GF":0,"gc":3,"DIF":-3,"puntos":0},
{"id":18,"Equipo":"FC Augsburg","jornada":2,"jugados":1,"PG":0,"PE":0,"PP":1,"GF":1,"gc":5,"DIF":-4,"puntos":0}]};