tablaJson = {"nodes":[
{"id":1,"Equipo":"Borussia Dortmund","jornada":2,"PJ":2,"PG":2,"PE":0,"PP":0,"GF":8,"GC":2,"DIF":6,"puntos":6},
{"id":2,"Equipo":"RB Leipzig","jornada":2,"PJ":2,"PG":2,"PE":0,"PP":0,"GF":6,"GC":1,"DIF":5,"puntos":6},
{"id":3,"Equipo":"SC Freiburg","jornada":2,"PJ":2,"PG":2,"PE":0,"PP":0,"GF":6,"GC":1,"DIF":5,"puntos":6},
{"id":4,"Equipo":"VfL Wolfsburg","jornada":2,"PJ":2,"PG":2,"PE":0,"PP":0,"GF":5,"GC":1,"DIF":4,"puntos":6},
{"id":5,"Equipo":"Bayer 04 Leverkusen","jornada":2,"PJ":2,"PG":2,"PE":0,"PP":0,"GF":6,"GC":3,"DIF":3,"puntos":6},
{"id":6,"Equipo":"Bayern Muenchen","jornada":2,"PJ":2,"PG":1,"PE":1,"PP":0,"GF":5,"GC":2,"DIF":3,"puntos":4},
{"id":7,"Equipo":"Bor. Moenchengladbach","jornada":2,"PJ":2,"PG":1,"PE":1,"PP":0,"GF":3,"GC":1,"DIF":2,"puntos":4},
{"id":8,"Equipo":"Fortuna Duesseldorf","jornada":2,"PJ":2,"PG":1,"PE":0,"PP":1,"GF":4,"GC":4,"DIF":0,"puntos":3},
{"id":9,"Equipo":"TSG Hoffenheim","jornada":2,"PJ":2,"PG":1,"PE":0,"PP":1,"GF":3,"GC":3,"DIF":0,"puntos":3},
{"id":10,"Equipo":"Eintracht Frankfurt","jornada":2,"PJ":2,"PG":1,"PE":0,"PP":1,"GF":2,"GC":2,"DIF":0,"puntos":3},
{"id":11,"Equipo":"Hertha BSC","jornada":2,"PJ":2,"PG":0,"PE":1,"PP":1,"GF":2,"GC":5,"DIF":-3,"puntos":1},
{"id":12,"Equipo":"FC Schalke 04","jornada":2,"PJ":2,"PG":0,"PE":1,"PP":1,"GF":0,"GC":3,"DIF":-3,"puntos":1},
{"id":13,"Equipo":"FC Augsburg","jornada":2,"PJ":2,"PG":0,"PE":1,"PP":1,"GF":2,"GC":6,"DIF":-4,"puntos":1},
{"id":14,"Equipo":"1. FC Union Berlin","jornada":2,"PJ":2,"PG":0,"PE":1,"PP":1,"GF":1,"GC":5,"DIF":-4,"puntos":1},
{"id":15,"Equipo":"SC Paderborn 07","jornada":2,"PJ":2,"PG":0,"PE":0,"PP":2,"GF":3,"GC":6,"DIF":-3,"puntos":0},
{"id":16,"Equipo":"Werder Bremen","jornada":2,"PJ":2,"PG":0,"PE":0,"PP":2,"GF":3,"GC":6,"DIF":-3,"puntos":0},
{"id":17,"Equipo":"1. FC Koeln","jornada":2,"PJ":2,"PG":0,"PE":0,"PP":2,"GF":2,"GC":5,"DIF":-3,"puntos":0},
{"id":18,"Equipo":"1. FSV Mainz 05","jornada":2,"PJ":2,"PG":0,"PE":0,"PP":2,"GF":1,"GC":6,"DIF":-5,"puntos":0}]};